// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `flatten_grid`, `unflatten_grid`, `update`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

GameStateView gameInit() => RustLib.instance.api.crateApiGameGameInit();

GameStateView gameTick({required GameStateView gsv}) =>
    RustLib.instance.api.crateApiGameGameTick(gsv: gsv);

GameStateView gameMoveLeft({required GameStateView gsv}) =>
    RustLib.instance.api.crateApiGameGameMoveLeft(gsv: gsv);

GameStateView gameMoveRight({required GameStateView gsv}) =>
    RustLib.instance.api.crateApiGameGameMoveRight(gsv: gsv);

GameStateView gameMoveDown({required GameStateView gsv}) =>
    RustLib.instance.api.crateApiGameGameMoveDown(gsv: gsv);

GameStateView gameRotateCw({required GameStateView gsv}) =>
    RustLib.instance.api.crateApiGameGameRotateCw(gsv: gsv);

GameStateView gameRotateCcw({required GameStateView gsv}) =>
    RustLib.instance.api.crateApiGameGameRotateCcw(gsv: gsv);

GameStateView gameSoftDrop({required GameStateView gsv}) =>
    RustLib.instance.api.crateApiGameGameSoftDrop(gsv: gsv);

GameStateView gameHardDrop({required GameStateView gsv}) =>
    RustLib.instance.api.crateApiGameGameHardDrop(gsv: gsv);

GameStateView gameHold({required GameStateView gsv}) =>
    RustLib.instance.api.crateApiGameGameHold(gsv: gsv);

/// FRB-friendly snapshot of the game state.
/// Grid is flat row-major Vec (200 elements): index = y * WIDTH + x
class GameStateView {
  final List<CellType> grid;
  final CellType currentPiece;
  final int currentRotation;
  final int currentX;
  final int currentY;
  final int ghostX;
  final int ghostY;
  final CellType? holdPiece;
  final bool canHold;
  final List<CellType> nextQueue;
  final int score;
  final int level;
  final int lines;
  final bool gameOver;
  final List<CellType> bagQueue;
  final PlatformInt64 bagRng;

  const GameStateView({
    required this.grid,
    required this.currentPiece,
    required this.currentRotation,
    required this.currentX,
    required this.currentY,
    required this.ghostX,
    required this.ghostY,
    this.holdPiece,
    required this.canHold,
    required this.nextQueue,
    required this.score,
    required this.level,
    required this.lines,
    required this.gameOver,
    required this.bagQueue,
    required this.bagRng,
  });

  @override
  int get hashCode =>
      grid.hashCode ^
      currentPiece.hashCode ^
      currentRotation.hashCode ^
      currentX.hashCode ^
      currentY.hashCode ^
      ghostX.hashCode ^
      ghostY.hashCode ^
      holdPiece.hashCode ^
      canHold.hashCode ^
      nextQueue.hashCode ^
      score.hashCode ^
      level.hashCode ^
      lines.hashCode ^
      gameOver.hashCode ^
      bagQueue.hashCode ^
      bagRng.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GameStateView &&
          runtimeType == other.runtimeType &&
          grid == other.grid &&
          currentPiece == other.currentPiece &&
          currentRotation == other.currentRotation &&
          currentX == other.currentX &&
          currentY == other.currentY &&
          ghostX == other.ghostX &&
          ghostY == other.ghostY &&
          holdPiece == other.holdPiece &&
          canHold == other.canHold &&
          nextQueue == other.nextQueue &&
          score == other.score &&
          level == other.level &&
          lines == other.lines &&
          gameOver == other.gameOver &&
          bagQueue == other.bagQueue &&
          bagRng == other.bagRng;
}
